name: firstworkflow # Workflow name

on:
  push:
    branches:
      - 'main'  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clone the repository

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Generate the human-readable timestamp for versioning
        id: version
        run: |
          VERSION=$(date +'%Y-%m-%d_%H-%M-%S')  # Human-readable format (e.g., 2025-02-17_10-15-30)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV  # Set the version as an environment variable
          echo "Built with version ${VERSION}"

      - name: Build the Docker image
        run: |
          docker build -t amitkumar0441/simplepythonapp:${{ env.VERSION }} .

      - name: List Docker images
        run: docker images

      - name: Push to Docker Hub
        run: |
          docker push amitkumar0441/simplepythonapp:${{ env.VERSION }}
