name: firstworkflow # Workflow name

on:
  push:
    branches:
      - 'main'  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clone the repository

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Read the current version
        id: get_version
        run: |
          VERSION_FILE="version.txt"
          if [ ! -f $VERSION_FILE ]; then
            echo "1" > $VERSION_FILE  # If version.txt doesn't exist, initialize with version 1
          fi
          VERSION=$(cat $VERSION_FILE)
          echo "Current version is $VERSION"
          echo "::set-output name=version::$VERSION"  # Set the version as an output

      - name: Increment the version
        run: |
          VERSION_FILE="version.txt"
          VERSION=$(cat $VERSION_FILE)
          NEW_VERSION=$((VERSION + 1))  # Increment version by 1
          echo "New version is $NEW_VERSION"
          echo $NEW_VERSION > $VERSION_FILE  # Save the new version to the file

      - name: Commit updated version file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add version.txt
          git commit -m "Increment version to ${{ steps.get_version.outputs.version }}"
          git push

      - name: Build the Docker image
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          docker build -t amitkumar0441/simplepythonapp:${VERSION} .

      - name: List Docker images
        run: docker images

      - name: Push to Docker Hub
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          docker push amitkumar0441/simplepythonapp:${VERSION}
