name: firstworkflow # Workflow name

on:
  push:
    branches:
      - 'main'  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clone the repository

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build the Docker image with date and time version
        run: |
          VERSION=$(date +'%Y%m%d-%H%M%S')  # Use current date and time as version
          echo "Building Docker image with tag ${VERSION}"
          docker build -t amitkumar0441/simplepythonapp:${VERSION} .

      - name: List Docker images
        run: docker images

      - name: Push to Docker Hub
        run: |
          VERSION=$(date +'%Y%m%d-%H%M%S')  # Ensure we use the same VERSION variable
          echo "Pushing Docker image with tag ${VERSION}"
          docker push amitkumar0441/simplepythonapp:${VERSION}
